spring:
  datasource:
    url: jdbc:mysql://43.201.246.74:3306/mapmories?serverTimezone=Asia/Seoul
    username: root
    password: 252525
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  application:
    name: mapmories
  security:
    user:
      name: user
      password: user

firebase:
  projectId: mapmories-e0aa7
